source 'https://rubygems.org'

ruby '3.2.4'

gem 'rails', '~> 7.1'

gem 'bootsnap', require: false
gem 'haml'
gem 'haml_lint', require: false
gem 'hotwire-rails'
gem 'importmap-rails'
gem 'jbuilder'
gem 'pg'
gem 'puma'
gem 'redis'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'turbo-rails'

group :development, :test do
  gem 'debug'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :development do
  gem 'letter_opener'
  gem 'pgreset'
  gem 'rubocop'
  gem 'rubocop-capybara', require: false
  gem 'rubocop-factory_bot'
  gem 'rubocop-minitest'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
end

group :test do
  gem 'capybara'
  gem 'mocha'
  gem 'selenium-webdriver'
  gem 'shoulda-context'
  gem 'shoulda-matchers'
end
